In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
import pandas as pd
import numpy as np
from mesh_import import mesh
import mesh.affix as affix
from mesh.affix import CkipAffixoids

/home/seantyh/langon/OntoDeepLex/src/mesh/cns.py:3: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [3]:
from mesh.affix import AffixoidCtmDataset


In [10]:
ctm_ds = AffixoidCtmDataset()

In [12]:
len(ctm_ds)

301320

In [9]:
a = next(iter(ex_store.values()))

In [11]:
a[0][0].shape

(18566,)

In [16]:
aff0 = proc.affixoids[0]
ex0 = aff0.example_words[2]

In [53]:
outs = proc.build_affixoid_examples(aff0, ex0[1])

In [21]:
affix_dir = mesh.get_data_dir() / "affix/"        
affixoids = CkipAffixoids(affix_dir)

In [22]:
len(affixoids)

4056

In [14]:
asbc_dir = mesh.get_data_dir() / "asbc"
with (asbc_dir/"asbc5_words.pkl").open("rb") as fin:
    words = pickle.load(fin)

In [16]:
len([x for x, f in words.items() if f > 100])

8515

In [56]:
outs[0]

[[array([2, 0, 0, ..., 0, 0, 0], dtype=int64),
  array([3, 0, 0, ..., 0, 0, 0], dtype=int64)]]

In [59]:
sentences = list(proc.asbc.query(ex0[1]))

In [60]:
sentences

[[('這', 'Nep'), ('一生', 'Na'), ('一世', 'Na'), ('，', 'COMMACATEGORY')],
 [('一生', 'Na'), ('一世', 'Na'), ('長相左右', 'VH'), ('。', 'PERIODCATEGORY')]]

In [70]:
[[[1,2], [1,2]], [[3,4], [3,4]]]

[[[1, 2], [1, 2]], [[3, 4], [3, 4]]]

In [127]:
outs = proc.build_affixoid_examples(aff0, ex0[1])

> e:\langon\ontodeeplex\src\mesh\affix\ctm_utils.py(146)build_batch_example()
-> affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]


(Pdb)  targ_token_indices


[4, 3]


(Pdb)  input_tensors


{'input_ids': tensor([[  101,  7734,  2072,  5600,  2072,  2087, 10064,   102,     0,     0,
             0],
        [  101,  2072,  5600,  2072,  2087,  8127,  5760,  3585,  2760,  1882,
           102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


(Pdb)  self.bert.decode([2072, 2087])


'一 世'


(Pdb)  q



Traceback (most recent call last):
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 111, in build_affixoid_examples
    bows, bert_vecs = self.build_batch_example(affixoid, word, batch_iter)
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 146, in build_batch_example
    affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 146, in build_batch_example
    affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]
  File "c:\python38\lib\bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "c:\python38\lib\bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit



In [125]:
isinstance(np.where(outs[0][0])[0], type(iter))

False

In [126]:
proc.vocab.decode(np.where(outs[0][0])[0].tolist())

['這', '一生', '一_.1']

In [99]:
list(proc.asbc.query(ex0[1]))

[[('這', 'Nep'), ('一生', 'Na'), ('一世', 'Na'), ('，', 'COMMACATEGORY')],
 [('一生', 'Na'), ('一世', 'Na'), ('長相左右', 'VH'), ('。', 'PERIODCATEGORY')]]

In [87]:
bow = outs[0]

In [101]:
bows, bert_vecs = proc.build_batch_example(aff0, ex0[1], list(proc.asbc.query(ex0[1]))) 

In [106]:
a = [bows, bows]; b = [bert_vecs, bert_vecs]

In [109]:
from itertools import chain

In [5]:
import torch
torch.tensor([1,0])*torch.tensor([0.5, 0])

tensor([0.5000, 0.0000])

In [129]:
ex_path = mesh.get_data_dir() / "affix/affixoid_ctm_examples.pkl"
import pickle
with ex_path.open("rb") as fin:
    examples = pickle.load(fin)


In [132]:
np.where(examples[0][0])

(array([  251,   282,   429,  5830, 14510], dtype=int64),)