In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import pickle
import pandas as pd
import numpy as np
from mesh_import import mesh
import mesh.affix as affix
from mesh.affix import CkipAffixoids

In [ ]:
from mesh.affix import AffixoidCtmDataset, AffixoidCtmProcessor


In [ ]:
proc = AffixoidCtmProcessor()

In [5]:
len(proc.vocab)

18566

In [6]:
proc.save_vocabulary()

In [8]:
ctm_ds = AffixoidCtmDataset()

In [9]:
len(ctm_ds)

301320

In [11]:
ctm_ds[0]

{'X': tensor([0., 0., 0.,  ..., 0., 0., 0.]),
 'X_bert': tensor([ 2.9411e-01, -5.7343e-01,  7.0287e-01,  5.6247e-01,  4.4728e-01,
          6.6858e-01, -2.8186e-02, -1.8115e-01, -4.9480e-01,  2.4081e-01,
          9.0828e-01,  2.0926e-01, -8.7753e-01, -2.1223e-01, -1.1924e-01,
          1.0756e-01,  7.7363e-01,  1.5668e-01, -3.0280e-01,  1.0090e-01,
         -3.1703e-02,  1.7063e-01,  6.6835e-02,  4.4900e-01, -7.6804e-01,
          2.8976e-01,  1.2600e-01, -2.3840e-02,  3.7979e-01, -7.7122e-01,
          7.4605e-01,  1.7287e-01, -9.4508e-01,  4.6727e-01, -3.6987e-02,
          9.3192e-01, -5.6421e-01,  1.7286e-01,  6.4512e-02, -4.5079e-01,
         -2.4702e-01, -5.8140e-01, -1.5683e-03,  3.7782e-01,  7.6067e-02,
          1.7270e-02,  3.9782e-02,  1.6075e-01,  2.5822e-01,  5.9981e-01,
         -3.1867e-01, -1.8331e-02, -5.1166e-01,  7.5814e-02, -5.2184e-01,
          1.1240e-01,  5.9839e-01, -8.0103e-01,  1.1564e-01,  1.5535e-01,
          1.7471e-02, -5.4497e-01, -2.2118e-01, -1.3294e

In [9]:
a = next(iter(ex_store.values()))

In [11]:
a[0][0].shape

(18566,)

In [16]:
aff0 = proc.affixoids[0]
ex0 = aff0.example_words[2]

In [53]:
outs = proc.build_affixoid_examples(aff0, ex0[1])

In [21]:
affix_dir = mesh.get_data_dir() / "affix/"        
affixoids = CkipAffixoids(affix_dir)

In [22]:
len(affixoids)

4056

In [14]:
asbc_dir = mesh.get_data_dir() / "asbc"
with (asbc_dir/"asbc5_words.pkl").open("rb") as fin:
    words = pickle.load(fin)

In [49]:
proc = affix.AffixoidCtmProcessor()

loading ASBC corpus streamer index


In [54]:
len(proc.build_vocab(words, proc.affixoids))

18566

In [55]:
len([x for x, f in words.items() if f >= 50])

14744

In [56]:
outs[0]

[[array([2, 0, 0, ..., 0, 0, 0], dtype=int64),
  array([3, 0, 0, ..., 0, 0, 0], dtype=int64)]]

In [59]:
sentences = list(proc.asbc.query(ex0[1]))

In [60]:
sentences

[[('這', 'Nep'), ('一生', 'Na'), ('一世', 'Na'), ('，', 'COMMACATEGORY')],
 [('一生', 'Na'), ('一世', 'Na'), ('長相左右', 'VH'), ('。', 'PERIODCATEGORY')]]

In [70]:
[[[1,2], [1,2]], [[3,4], [3,4]]]

[[[1, 2], [1, 2]], [[3, 4], [3, 4]]]

In [127]:
outs = proc.build_affixoid_examples(aff0, ex0[1])

> e:\langon\ontodeeplex\src\mesh\affix\ctm_utils.py(146)build_batch_example()
-> affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]


(Pdb)  targ_token_indices


[4, 3]


(Pdb)  input_tensors


{'input_ids': tensor([[  101,  7734,  2072,  5600,  2072,  2087, 10064,   102,     0,     0,
             0],
        [  101,  2072,  5600,  2072,  2087,  8127,  5760,  3585,  2760,  1882,
           102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


(Pdb)  self.bert.decode([2072, 2087])


'一 世'


(Pdb)  q



Traceback (most recent call last):
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 111, in build_affixoid_examples
    bows, bert_vecs = self.build_batch_example(affixoid, word, batch_iter)
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 146, in build_batch_example
    affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]
  File "E:\LangOn\OntoDeepLex\src\mesh\affix\ctm_utils.py", line 146, in build_batch_example
    affix_vecs = outputs[np.arange(len(targ_token_indices)), targ_token_indices, :]
  File "c:\python38\lib\bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "c:\python38\lib\bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit



In [125]:
isinstance(np.where(outs[0][0])[0], type(iter))

False

In [126]:
proc.vocab.decode(np.where(outs[0][0])[0].tolist())

['這', '一生', '一_.1']

In [99]:
list(proc.asbc.query(ex0[1]))

[[('這', 'Nep'), ('一生', 'Na'), ('一世', 'Na'), ('，', 'COMMACATEGORY')],
 [('一生', 'Na'), ('一世', 'Na'), ('長相左右', 'VH'), ('。', 'PERIODCATEGORY')]]

In [87]:
bow = outs[0]

In [101]:
bows, bert_vecs = proc.build_batch_example(aff0, ex0[1], list(proc.asbc.query(ex0[1]))) 

In [106]:
a = [bows, bows]; b = [bert_vecs, bert_vecs]

In [109]:
from itertools import chain

In [5]:
import torch
torch.tensor([1,0])*torch.tensor([0.5, 0])

tensor([0.5000, 0.0000])

In [129]:
ex_path = mesh.get_data_dir() / "affix/affixoid_ctm_examples.pkl"
import pickle
with ex_path.open("rb") as fin:
    examples = pickle.load(fin)


In [132]:
np.where(examples[0][0])

(array([  251,   282,   429,  5830, 14510], dtype=int64),)